/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type CallToAction = {
  _type: "callToAction";
  heading: string;
  text?: string;
  buttonText?: string;
  link?: Link;
};

export type Link = {
  _type: "link";
  linkType?: "href" | "page" | "post";
  href?: string;
  page?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "page";
  };
  post?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "post";
  };
  openInNewTab?: boolean;
};

export type InfoSection = {
  _type: "infoSection";
  heading?: string;
  subheading?: string;
  content?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      linkType?: "href" | "page" | "post";
      href?: string;
      page?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "page";
      };
      post?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "post";
      };
      openInNewTab?: boolean;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type BlockContent = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
  listItem?: "bullet" | "number";
  markDefs?: Array<{
    linkType?: "href" | "page" | "post";
    href?: string;
    page?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "page";
    };
    post?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "post";
    };
    openInNewTab?: boolean;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type Settings = {
  _id: string;
  _type: "settings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      linkType?: "href" | "page" | "post";
      href?: string;
      page?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "page";
      };
      post?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "post";
      };
      openInNewTab?: boolean;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  ogImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    metadataBase?: string;
    _type: "image";
  };
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  heading: string;
  subheading?: string;
  pageBuilder?: Array<{
    _key: string;
  } & CallToAction | {
    _key: string;
  } & InfoSection>;
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  content?: BlockContent;
  excerpt?: string;
  coverImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  date?: string;
  author?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "person";
  };
};

export type Person = {
  _id: string;
  _type: "person";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  firstName: string;
  lastName: string;
  picture: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
};

export type SanityAssistInstructionTask = {
  _type: "sanity.assist.instructionTask";
  path?: string;
  instructionKey?: string;
  started?: string;
  updated?: string;
  info?: string;
};

export type SanityAssistTaskStatus = {
  _type: "sanity.assist.task.status";
  tasks?: Array<{
    _key: string;
  } & SanityAssistInstructionTask>;
};

export type SanityAssistSchemaTypeAnnotations = {
  _type: "sanity.assist.schemaType.annotations";
  title?: string;
  fields?: Array<{
    _key: string;
  } & SanityAssistSchemaTypeField>;
};

export type SanityAssistOutputType = {
  _type: "sanity.assist.output.type";
  type?: string;
};

export type SanityAssistOutputField = {
  _type: "sanity.assist.output.field";
  path?: string;
};

export type SanityAssistInstructionContext = {
  _type: "sanity.assist.instruction.context";
  reference: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "assist.instruction.context";
  };
};

export type AssistInstructionContext = {
  _id: string;
  _type: "assist.instruction.context";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  context?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: null;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type SanityAssistInstructionUserInput = {
  _type: "sanity.assist.instruction.userInput";
  message: string;
  description?: string;
};

export type SanityAssistInstructionPrompt = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  } | {
    _key: string;
  } & SanityAssistInstructionFieldRef | {
    _key: string;
  } & SanityAssistInstructionContext | {
    _key: string;
  } & SanityAssistInstructionUserInput>;
  style?: "normal";
  listItem?: never;
  markDefs?: null;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type SanityAssistInstructionFieldRef = {
  _type: "sanity.assist.instruction.fieldRef";
  path?: string;
};

export type SanityAssistInstruction = {
  _type: "sanity.assist.instruction";
  prompt?: SanityAssistInstructionPrompt;
  icon?: string;
  title?: string;
  userId?: string;
  createdById?: string;
  output?: Array<{
    _key: string;
  } & SanityAssistOutputField | {
    _key: string;
  } & SanityAssistOutputType>;
};

export type SanityAssistSchemaTypeField = {
  _type: "sanity.assist.schemaType.field";
  path?: string;
  instructions?: Array<{
    _key: string;
  } & SanityAssistInstruction>;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type AllSanitySchemaTypes = CallToAction | Link | InfoSection | BlockContent | Settings | Page | Post | Person | SanityAssistInstructionTask | SanityAssistTaskStatus | SanityAssistSchemaTypeAnnotations | SanityAssistOutputType | SanityAssistOutputField | SanityAssistInstructionContext | AssistInstructionContext | SanityAssistInstructionUserInput | SanityAssistInstructionPrompt | SanityAssistInstructionFieldRef | SanityAssistInstruction | SanityAssistSchemaTypeField | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageHotspot | SanityImageCrop | SanityFileAsset | SanityImageAsset | SanityImageMetadata | Geopoint | Slug | SanityAssetSourceData;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./sanity/lib/analyticsQueries.ts
// Variable: pageViewsQuery
// Query: *[_type == "pageView"] | order(recordedAt desc) [$from...$to] {    _id,    url,    sessionId,    ipAddress,    hostname,    userAgent,    loadTimeMs,    referrer,    recordedAt  }
export type PageViewsQueryResult = Array<never>;
// Variable: pageViewsCountQuery
// Query: count(*[_type == "pageView"])
export type PageViewsCountQueryResult = number;
// Variable: userEventsQuery
// Query: *[_type == "userEvent"] | order(recordedAt desc) [$from...$to] {    _id,    eventType,    eventName,    url,    sessionId,    ipAddress,    hostname,    metadata,    recordedAt  }
export type UserEventsQueryResult = Array<never>;
// Variable: userEventsCountQuery
// Query: count(*[_type == "userEvent"])
export type UserEventsCountQueryResult = number;
// Variable: errorLogsQuery
// Query: *[_type == "errorLog"] | order(recordedAt desc) [$from...$to] {    _id,    errorType,    message,    severity,    url,    ipAddress,    hostname,    stackTrace,    status,    recordedAt  }
export type ErrorLogsQueryResult = Array<never>;
// Variable: errorLogsCountQuery
// Query: count(*[_type == "errorLog"])
export type ErrorLogsCountQueryResult = number;
// Variable: systemMetricsQuery
// Query: *[_type == "systemMetric"] | order(recordedAt desc) [$from...$to] {    _id,    metricType,    value,    unit,    status,    recordedAt  }
export type SystemMetricsQueryResult = Array<never>;
// Variable: systemMetricsCountQuery
// Query: count(*[_type == "systemMetric"])
export type SystemMetricsCountQueryResult = number;
// Variable: performanceMetricsQuery
// Query: *[_type == "performanceMetric"] | order(recordedAt desc) [$from...$to] {    _id,    metric,    value,    url,    sessionId,    ipAddress,    hostname,    recordedAt  }
export type PerformanceMetricsQueryResult = Array<never>;
// Variable: performanceMetricsCountQuery
// Query: count(*[_type == "performanceMetric"])
export type PerformanceMetricsCountQueryResult = number;
// Variable: resumeDownloadsQuery
// Query: *[_type == "resumeDownload"] | order(recordedAt desc) [$from...$to] {    _id,    ipAddress,    hostname,    userAgent,    sessionId,    referrer,    recordedAt  }
export type ResumeDownloadsQueryResult = Array<never>;
// Variable: resumeDownloadsCountQuery
// Query: count(*[_type == "resumeDownload"])
export type ResumeDownloadsCountQueryResult = number;

// Source: ./sanity/lib/queries.ts
// Variable: settingsQuery
// Query: *[_type == "settings"][0]
export type SettingsQueryResult = {
  _id: string;
  _type: "settings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      linkType?: "href" | "page" | "post";
      href?: string;
      page?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "page";
      };
      post?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "post";
      };
      openInNewTab?: boolean;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  ogImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    metadataBase?: string;
    _type: "image";
  };
} | null;
// Variable: sourceCodesQuery
// Query: *[_type == "sourceCode" && isPublished == true] | order(publishedAt desc) {    _id,    title,    "slug": slug.current,    description,    githubUrl,    demoUrl,    price,    "mainImage": mainImage.asset->url,    "images": images[].asset->url,    technologies,    features,    readme,    publishedAt  }
export type SourceCodesQueryResult = Array<never>;
// Variable: resumeQuery
// Query: *[_type == "docFile" && category == "resume" && isPublic == true][0] {    _id,    name,    description,    "fileUrl": file.asset->url,    uploadedAt  }
export type ResumeQueryResult = null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "\n  *[_type == \"pageView\"] | order(recordedAt desc) [$from...$to] {\n    _id,\n    url,\n    sessionId,\n    ipAddress,\n    hostname,\n    userAgent,\n    loadTimeMs,\n    referrer,\n    recordedAt\n  }\n": PageViewsQueryResult;
    "\n  count(*[_type == \"pageView\"])\n": PageViewsCountQueryResult;
    "\n  *[_type == \"userEvent\"] | order(recordedAt desc) [$from...$to] {\n    _id,\n    eventType,\n    eventName,\n    url,\n    sessionId,\n    ipAddress,\n    hostname,\n    metadata,\n    recordedAt\n  }\n": UserEventsQueryResult;
    "\n  count(*[_type == \"userEvent\"])\n": UserEventsCountQueryResult;
    "\n  *[_type == \"errorLog\"] | order(recordedAt desc) [$from...$to] {\n    _id,\n    errorType,\n    message,\n    severity,\n    url,\n    ipAddress,\n    hostname,\n    stackTrace,\n    status,\n    recordedAt\n  }\n": ErrorLogsQueryResult;
    "\n  count(*[_type == \"errorLog\"])\n": ErrorLogsCountQueryResult;
    "\n  *[_type == \"systemMetric\"] | order(recordedAt desc) [$from...$to] {\n    _id,\n    metricType,\n    value,\n    unit,\n    status,\n    recordedAt\n  }\n": SystemMetricsQueryResult;
    "\n  count(*[_type == \"systemMetric\"])\n": SystemMetricsCountQueryResult;
    "\n  *[_type == \"performanceMetric\"] | order(recordedAt desc) [$from...$to] {\n    _id,\n    metric,\n    value,\n    url,\n    sessionId,\n    ipAddress,\n    hostname,\n    recordedAt\n  }\n": PerformanceMetricsQueryResult;
    "\n  count(*[_type == \"performanceMetric\"])\n": PerformanceMetricsCountQueryResult;
    "\n  *[_type == \"resumeDownload\"] | order(recordedAt desc) [$from...$to] {\n    _id,\n    ipAddress,\n    hostname,\n    userAgent,\n    sessionId,\n    referrer,\n    recordedAt\n  }\n": ResumeDownloadsQueryResult;
    "\n  count(*[_type == \"resumeDownload\"])\n": ResumeDownloadsCountQueryResult;
    "*[_type == \"settings\"][0]": SettingsQueryResult;
    "\n  *[_type == \"sourceCode\" && isPublished == true] | order(publishedAt desc) {\n    _id,\n    title,\n    \"slug\": slug.current,\n    description,\n    githubUrl,\n    demoUrl,\n    price,\n    \"mainImage\": mainImage.asset->url,\n    \"images\": images[].asset->url,\n    technologies,\n    features,\n    readme,\n    publishedAt\n  }\n": SourceCodesQueryResult;
    "\n  *[_type == \"docFile\" && category == \"resume\" && isPublic == true][0] {\n    _id,\n    name,\n    description,\n    \"fileUrl\": file.asset->url,\n    uploadedAt\n  }\n": ResumeQueryResult;
  }
}
