// Experience data parsed from resume
export const experienceData = {
  positions: [
    {
      id: 1,
      company: "Cefalo",
      companyLink: "https://cefalo.com",
      location: "Dhaka, Bangladesh",
      position: "Senior Software Engineer",
      duration: "2020–2024",
      architectures: [
        "Distributed Systems",
        "Microservices",
        "Event Driven Architecture",
      ],
      applications: [
        {
          title: "SportsData",
          link: "https://www.ntb.no/sport/sportsdata",
          countries: ["Norway", "Denmark", "Sweden", "Finland", "Iceland"],
        },
      ],
      achievements: [
        "Enterprise Sports Data API Development: Architected and developed a comprehensive multilingual sports data API solution for <strong><a href='https://www.ntb.no/' target='_blank' rel='noopener noreferrer'>NTB</a></strong>, Norway's premier news agency, enabling real-time broadcasting of winter sports data across European markets. The platform covers major international sporting events including <strong>World Cup</strong>, <strong>World Championship</strong>, <strong>Grand Prix</strong>, <strong>Winter & Summer Olympics</strong> and many more, serving as the primary data source for leading Norwegian broadcasters including <strong><a href='https://resultater.nrk.no/vintersport/hopp/2025-08-09/event/70173c79-387a-4cb5-b700-d4adc012b947' target='_blank' rel='noopener noreferrer'>NRK</a></strong>, <strong><a href='https://www.tv2.no/' target='_blank' rel='noopener noreferrer'>TV2</a></strong>, and <strong><a href='https://www.direktesport.no/vintersport' target='_blank' rel='noopener noreferrer'>Nettavisen</a></strong>. Additionally, engineered comprehensive internal tools and services, including broadcasting service orchestration, standings calculation engines, results service management, and data export utilities.",
        "Infrastructure and DevOps: Developed a cache invalidation service for database-driven cache management and worked with cloud automation tools including Bitbucket CI, TeamCity, Octopus, and AWS for CI/CD pipelines. Implemented comprehensive testing strategies including unit, API, and integration testing frameworks for application quality assurance.",
        "Neo4j Query Framework: Architected and developed a comprehensive Neo4j query framework for enterprise clients, enabling developers to construct complex Cypher queries with significantly reduced code complexity and improved error handling. The framework addresses the challenge of managing heavily aggregated node traversals in complex Cypher queries by providing an intuitive abstraction layer. This solution successfully consolidated thousands of lines of Cypher queries into concise, maintainable 20-30 line implementations while enhancing query performance and developer productivity.",
      ],
      technologies: [
        "GraphQL",
        "ReactJS",
        "AWS",
        "Neo4j",
        "Bitbucket CI",
        "TeamCity",
        "Octopus",
        "S3",
        "SNS",
        "SQS",
        "RDS",
        "EC2",
        "Postgres",
        "Docker",
        "Typescript",
        "REST APIs",
      ],
    },
    {
      id: 2,
      company: "Kickbackapps Inc.",
      companyLink: "https://kickbackapps.com",
      location: "Dhaka, Bangladesh",
      position: "Software Engineer",
      duration: "2019–2020",
      architectures: ["Distributed Systems", "Microservices", "Monoliths"],
      applications: [
        {
          title: "PhoneLine",
          link: "https://www.phonelineapp.com/",
          countries: ["United States", "Canada", "United Kingdom"],
        },
        {
          title: "GhostCall",
          link: "https://apkpure.com/ghostcall-private-sms-call/com.kickbackapps.ghostcall",
          countries: ["United States", "Canada", "United Kingdom"],
        },
        {
          title: "PrankDial",
          link: "https://www.prankdial.com/us",
          countries: [
            "United States",
            "Canada",
            "United Kingdom",
            "Italy",
            "Spain",
            "Mexico",
            "Germany",
            "France",
            "Ireland",
            "Australia",
          ],
        },
        {
          title: "Chatflix",
          link: "#",
          countries: ["Bangladesh"],
        },
        {
          title: "Cogman UI",
          link: "#",
          countries: ["Bangladesh"],
        },
        {
          title: "Gokada",
          link: "https://www.gokada.ng/",
          countries: ["Nigeria"],
        },
      ],
      achievements: [
        "Backend Development: Engineered and maintained backend services for multiple applications including <strong>PhoneLine</strong>, <strong>Gokada</strong>, <strong>Prankdial</strong>, and <strong>Chatflix</strong>. Integrated third-party VOIP plugins such as Twilio, Plivo, and InfoBIP, implemented multi-layered security features, rate limiting, and RBAC systems. Developed key operational services and architected a task queue management administrative tool.",
      ],
      technologies: [
        "Golang",
        "NodeJS",
        "ReactJS",
        "Twilio",
        "Plivo",
        "InfoBIP",
        "MongoDB",
        "PHP",
        "Laravel",
        "MySQL",
        "Docker",
        "CI/CD",
        "AWS",
        "S3",
      ],
    },
    {
      id: 3,
      company: "Shimahin Limited",
      companyLink: "https://shophobe.com",
      location: "Dhaka, Bangladesh",
      position: "Software Engineer",
      duration: "2018–2019",
      architectures: ["Distributed Systems", "Microservices"],
      applications: [
        {
          title: "Shophobe",
          link: "#",
          countries: ["Bangladesh"],
        },
      ],
      achievements: [
        "Backend development: My responsibilities were building microservices and APIs for key operational services including order processing, delivery management, payment gateway integration, social-networking platform integration, Ecommerce store and other third party plugin integrations.",
      ],
      technologies: [
        "Microservices",
        "APIs",
        "Payment Gateway",
        "Ecommerce",
        "Graph API",
        "Golang",
        "Couchbase",
        "Redis",
        "Docker",
      ],
    },
  ],
  stats: {
    totalYears: 8,
    companies: 3,
    projects: 15,
    technologies: 25,
  },
  skills: {
    frontend: ["ReactJS", "GraphQL", "TypeScript", "JavaScript", "HTML", "CSS"],
    backend: ["Node.js", "Python", "Java", "Microservices", "APIs", "REST"],
    cloud: ["AWS", "S3", "SNS", "SQS", "RDS", "EC2", "CI/CD"],
    database: ["Neo4j", "MongoDB", "PostgreSQL", "MySQL"],
    tools: ["Bitbucket CI", "TeamCity", "Octopus", "Docker", "Git"],
  },
};
